---
abstract: 'Tags helper for table view.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  CSS::Struct::Output::Raw: 0
  CSS::Struct::Output::Structure: 0
  ExtUtils::MakeMaker: 6.59
  Tags::Output::Raw: 0
  Tags::Output::Structure: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tags-HTML-Table-View
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0
  Error::Pure: 0
  List::MoreUtils: 0
  Tags::HTML: 0.06
  Tags::HTML::Element::A: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Tags-HTML-Table-View/issues
  homepage: https://github.com/michal-josef-spacek/Tags-HTML-Table-View
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Tags-HTML-Table-View
version: '0.04'
